# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-01-21T15:54:33+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class CareerPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    company: str
    enabled: bool | None = None
    extra_keywords: list[str] | None = Field(None, alias="extra-keywords")
    keywords: list[str] | None = None
    url: str


class JobAdd(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    browser: bool | None = None
    model: str | None = None
    structured: bool | None = None


class JobExport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    output: str | None = None
    output_format: str | None = Field(None, alias="output-format")


class JobFit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cv: str | None = None
    extra: list[str] | None = None
    model: str | None = None


class JobGH(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auto_assign: bool | None = Field(None, alias="auto-assign")
    default_labels: list[str] | None = Field(None, alias="default-labels")
    repo: str | None = None


class JobSearch(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    in_: list[CareerPage] | None = Field(None, alias="in")
    keywords: list[str] | None = None
    parallel: bool | None = None
    since: int | None = None


class JobSettings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    add: JobAdd | None = None
    db_path: str | None = Field(None, alias="db-path")
    export: JobExport | None = None
    fit: JobFit | None = None
    gh: JobGH | None = None
    model: str | None = None
    search: JobSearch | None = None
    verbose: bool | None = None


class CareerPage1(RootModel[Any]):
    root: Any


class JobSearch1(RootModel[Any]):
    root: Any


class JobGH1(RootModel[Any]):
    root: Any


class JobFit1(RootModel[Any]):
    root: Any


class JobAdd1(RootModel[Any]):
    root: Any


class JobExport1(RootModel[Any]):
    root: Any


class JobSettings1(RootModel[Any]):
    root: Any


class Model(BaseModel):
    job: JobSettings | None = None
